// Cart action types
export const CART_ACTIONS = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
  CLEAR_CART: 'CLEAR_CART',
  TOGGLE_CART: 'TOGGLE_CART',
  APPLY_DISCOUNT: 'APPLY_DISCOUNT',
  CALCULATE_TOTALS: 'CALCULATE_TOTALS',
  SET_CART_DATA: 'SET_CART_DATA',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR'
};
